set nocompatible
execute pathogen#infect()
set background=dark
" source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set tabpagemax=15
set history=1000

syntax on
set mouse=a
colorscheme solarized
set showmode

set laststatus=2

set backspace=indent,eol,start
set linespace=0

filetype plugin indent on

set number
set ruler
set showcmd
set incsearch
set hlsearch
set ignorecase
set smartcase

set wildmenu
set wildmode=list:longest,full

set scrolljump=5
set scrolloff=3

set foldenable
set foldmethod=indent
set foldlevelstart=10
set foldnestmax=10

set nolist
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

set nowrap
set autoindent
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set modelines=1

set vb t_vb=

let mapleader = ','

nnoremap <silent> <leader><space> :nohlsearch<CR>
nnoremap <silent> <F7> :set list!<CR>

if has('gui_running')
    set guioptions-=T
    set lines=40
else
    set term=builtin_ansi
endif

if has('gui_macvim')
   set guifont=Menlo
else
   set guifont=DejaVu_Sans_Mono:h9:cANSI
endif

if has('vms')
    set nobackup
else
    set backup
endif

" Functions {{{
" set diffexpr=MyDiff()
" function MyDiff()
"     let opt = '-a --binary '
"     if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
"     if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
"     let arg1 = v:fname_in
"     if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
"     let arg2 = v:fname_new
"     if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
"     let arg3 = v:fname_out
"     if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
"     let eq = ''
"     if $VIMRUNTIME =~ ' '
"	if &sh =~ '\<cmd'
"	    let cmd = '""' . $VIMRUNTIME . '\diff"'
"	    let eq = '"'
"	else
" 	    let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
"	endif
"    else
"	let cmd = $VIMRUNTIME . '\diff'
"    endif
"    silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
"endfunction
" }}}
"
" vim:foldmethod=marker:foldlevel=0
